In [1]:
import pandas as pd
import openai
import os
from dotenv import load_dotenv

# .env 파일에 정의된 환경 변수를 로드합니다.
load_dotenv()

# 로드된 환경 변수에서 API 키를 가져옵니다.
upstage_api_key = os.getenv("UPSTAGE_API_KEY")

In [4]:
# Upstage API와 통신할 클라이언트를 초기화합니다.
# 제공해주신 예시 코드를 기반으로 설정합니다.
client = openai.OpenAI(
    base_url="https://api.upstage.ai/v1",
    api_key=upstage_api_key,
)

In [ ]:
response = client.chat.completions.create(
    model="solar-pro2",
    messages=[
        {
            "role": "user",
            "content": "동원 참치가 뭔지 알아?"
        }
    ]
)
    # 응답을 출력합니다.
print(response.choices[0].message.content)

동원 참치(Dongwon Tuna)는 한국의 대표적인 수산물 기업인 **동원산업**에서 생산하는 참치 통조림 브랜드입니다. 1982년 출시된 이후의 대표 상품으로, 국내 참치 시장에서 큰 점유율을 차지하며 대중적인 인기를 끌고 있습니다.

### 주요 특징:
1. **제품 라인업**:
   - 참치마요, 고추참치, 참치샐러드 등 다양한 맛의 통조림 제품.
   - 고급 라인으로 **동원 특선 참치** (통째로 사용한 스테이크 형태) 등도 있습니다.
   - 최근에는 편의점용 소포장 제품(예: 동원 한끼 참치)도 출시.

2. **원재료**:
   - 주로 **가다랑어**(Skipjack Tuna) 또는 **황다랑어**(Yellowfin Tuna)를 사용하며, 지속 가능한 어업을 위한 **MSC 인증** 제품도 일부 있습니다.

3. **특징**:
   - 한국 소비자의 입맛에 맞춘 양념(매콤한 맛, 마요네즈 등)이 강점.
   - 합리적인 가격대와 편의성으로 일상식으로 자주 소비됩니다.

4. **논란**:
   - 과거 일부 제품에서 **수은 함량** 논란이 있었으나, 현재는 국제 기준(WHO/FAO) 이하로 관리됩니다.
   - 환경단체로부터 **원양 어업의 과잉 어획** 문제 제기되기도 했습니다.

### 활용 팁:
- 밥과 비벼 먹거나, 김치찌개·볶음밥 재료로 활용.
- 해외에서도 한국인 이민자들이 찾는 대표 간식 중 하나입니다.

궁금한 특정 제품이 있다면 더 자세히 알려드릴 수 있어요! 🐟

1. 브랜드
2. 내용물 종류(살코기, 고추참치, 야채참치)
3. 용량
4. 가격

## 양반, 동원, 덴마크, 그릴리, 비비드,  만 뽑고 나머지 drop (GNC)

In [24]:
import pandas as pd
import numpy as np

df= pd.read_csv('data/동원몰 리뷰순 상품(3차 카테고리).csv', encoding='utf-8')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36510 entries, 0 to 36509
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   1차 카테고리  36510 non-null  object
 1   2차 카테고리  36510 non-null  object
 2   3차 카테고리  36510 non-null  object
 3   페이지      36510 non-null  int64
 4   상품명      36510 non-null  object
 5   중량 수치    15986 non-null  object
 6   중량 단위    15986 non-null  object
 7   수량       7872 non-null   object
 8   수량 단위    5879 non-null   object
 9   가격       36510 non-null  int64
 10  평점       36510 non-null  float64
 11  리뷰 수     36510 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 3.3+ MB

In [26]:
# df의 상품명 컬럼에 양반, 동원, 덴마크, 그릴리, 비비드 중에 하나라도 들어간 행은 살려두고 나머지 열은 drop하고 인덱스 정리
df = df[df['상품명'].str.contains('양반|동원|덴마크|그릴리|비비드', na=False)]
df.reset_index(drop=True, inplace=True)
df

,1차 카테고리,2차 카테고리,3차 카테고리,페이지,상품명,중량 수치,중량 단위,수량,수량 단위,가격,평점,리뷰 수
0,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 85g x 20캔,85,g,20,캔,31900,5.0,2304
1,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔,"150, 200","g, g","10, 10","캔, 캔",49200,4.9,1467
2,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 150g x 5캔,150,g,5,캔,12300,4.9,845
3,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 150g x 20캔,150,g,20,캔,50000,4.9,899
4,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 85g x 10캔,85,g,10,캔,16600,4.9,905
...,...,...,...,...,...,...,...,...,...,...,...,...
1020,반려동식물,강아지 식품,캔/파우치,1,[아르르 X 동원] 더 건강한 쮸르 참치&참치알 14g x 120p,14,g,120,NaN,63900,5.0,1
1021,반려동식물,강아지 식품,스틱/저키,1,[아르르 X 동원] 더 건강한 쮸르 참치&참치알(10P),NaN,NaN,NaN,NaN,5900,5.0,6
1022,반려동식물,강아지 식품,스틱/저키,1,[아르르 X 동원] 더 건강한 쮸르 닭&크랜베리(10P),NaN,NaN,NaN,NaN,5900,5.0,4
1023,반려동식물,강아지 식품,스틱/저키,1,[아르르 X 동원] 더 건강한 쮸르 닭&크랜베리(10P) x 6개,NaN,NaN,NaN,NaN,32900,5.0,1
1024,반려동식물,강아지 식품,스틱/저키,1,[아르르 X 동원] 더 건강한 쮸르 참치&참치알(10P) x 6개,NaN,NaN,NaN,NaN,32900,5.0,1

In [27]:
# 1차 카테고리의 모든 종류 확인
df['1차 카테고리'].unique()

array(['통조림/즉석/면류', '과자/떡/베이커리', '냉장/냉동/간편식', '김치/반찬/양념', '과일/채소/쌀',
       '건강식품', '주방용품', '생활/유아동', '반려동식물'], dtype=object)

In [28]:
df = df[~df['1차 카테고리'].isin(['반려동식물', '주방용품', '생활/유아동', '과일/채소/쌀', '건강식품'])]
df.reset_index(drop=True, inplace=True)

In [29]:
# df에서 1차 카테고리와 2차 카테고리와 3차 카테고리 컬럼과 페이지 컬럼 제거
df = df.drop(columns=['1차 카테고리', '2차 카테고리', '3차 카테고리', '페이지'])
df

,상품명,중량 수치,중량 단위,수량,수량 단위,가격,평점,리뷰 수
0,동원참치 살코기 라이트스탠다드 85g x 20캔,85,g,20,캔,31900,5.0,2304
1,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔,"150, 200","g, g","10, 10","캔, 캔",49200,4.9,1467
2,동원참치 살코기 라이트스탠다드 150g x 5캔,150,g,5,캔,12300,4.9,845
3,동원참치 살코기 라이트스탠다드 150g x 20캔,150,g,20,캔,50000,4.9,899
4,동원참치 살코기 라이트스탠다드 85g x 10캔,85,g,10,캔,16600,4.9,905
...,...,...,...,...,...,...,...,...
754,동원홈푸드 비비드키친 알룰로스 510g,510,g,NaN,NaN,8580,4.9,10
755,동원 요리 올리고당 700ml,700,ml,NaN,NaN,3900,5.0,3
756,동원홈푸드 비비드키친 알룰로스 510g x 2개,510,g,2,개,15900,4.0,3
757,[4%적립금] 동원 빵가루 1kg x 8개(1박스),1,kg,8,개,28000,5.0,10
758,식자재 아울렛 동원홈푸드 파마산블렌드 227g,227,g,NaN,NaN,7190,0.0,0

In [31]:
df.to_csv('data/1차_컨조인트_정리.csv', index=False, encoding='utf-8-sig')

In [35]:
df1 = pd.read_csv('data/1차_컨조인트_정리.csv', encoding='utf-8-sig')

In [36]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 759 entries, 0 to 758
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   상품명     759 non-null    object
 1   중량 수치   755 non-null    object
 2   중량 단위   755 non-null    object
 3   수량      500 non-null    object
 4   수량 단위   496 non-null    object
 5   가격      759 non-null    int64
 6   평점      759 non-null    float64
 7   리뷰 수    759 non-null    int64
dtypes: float64(1), int64(2), object(5)
memory usage: 47.6+ KB

In [37]:
df1.tail(10)

                              상품명 중량 수치 중량 단위   수량 수량 단위     가격   평점  리뷰 수
749              [1+1]동원 참치다시 1kg     1    kg  NaN   NaN  19980  5.0     1
750                   동원 참치다시 2kg     2    kg  NaN   NaN  26980  0.0     0
751           [2+2] 동원 참치액 순 900g   900     g  NaN   NaN  25960  0.0     0
752              동원 참치액 순 900gx3개   900     g    3     개  27000  0.0     0
753           [1+1] 동원 참치액 순 900g   900     g  NaN   NaN  12980  4.7     3
754         동원홈푸드 비비드키친 알룰로스 510g   510     g  NaN   NaN   8580  4.9    10
755              동원 요리 올리고당 700ml   700    ml  NaN   NaN   3900  5.0     3
756    동원홈푸드 비비드키친 알룰로스 510g x 2개   510     g    2     개  15900  4.0     3
757  [4%적립금] 동원 빵가루 1kg x 8개(1박스)     1    kg    8     개  28000  5.0    10
758     식자재 아울렛 동원홈푸드 파마산블렌드 227g   227     g  NaN   NaN   7190  0.0     0

In [41]:
df1.drop(columns=['평점', '리뷰 수'], inplace=True)

In [42]:
df1

                                    상품명     중량 수치 중량 단위      수량 수량 단위     가격
0            동원참치 살코기 라이트스탠다드 85g x 20캔        85     g      20     캔  31900
1    동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔  150, 200  g, g  10, 10  캔, 캔  49200
2            동원참치 살코기 라이트스탠다드 150g x 5캔       150     g       5     캔  12300
3           동원참치 살코기 라이트스탠다드 150g x 20캔       150     g      20     캔  50000
4            동원참치 살코기 라이트스탠다드 85g x 10캔        85     g      10     캔  16600
..                                  ...       ...   ...     ...   ...    ...
754               동원홈푸드 비비드키친 알룰로스 510g       510     g     NaN   NaN   8580
755                    동원 요리 올리고당 700ml       700    ml     NaN   NaN   3900
756          동원홈푸드 비비드키친 알룰로스 510g x 2개       510     g       2     개  15900
757        [4%적립금] 동원 빵가루 1kg x 8개(1박스)         1    kg       8     개  28000
758           식자재 아울렛 동원홈푸드 파마산블렌드 227g       227     g     NaN   NaN   7190

[759 rows x 6 columns]

In [44]:
df1.to_csv('data/1차_컨조인트_정리_최종.csv', index=False, encoding='utf-8-sig')

- 참치캔 구매 상황 컨조인트 분석 설계
- 속성 및 속성 수준 <br>
속성 1: 참치 종류

수준: 살코기 참치, 고추 참치, 야채 참치

속성 2: 캔 용량

수준: 85g, 150g, 250g

속성 3: 묶음 수량

수준: 3개입, 10개입, 20개입

속성 4: 가격

수준: 10,000원, 25,000원, 45,000원