In [1]:
import pandas as pd
import openai
import os
from dotenv import load_dotenv

# .env 파일에 정의된 환경 변수를 로드합니다.
load_dotenv()

# 로드된 환경 변수에서 API 키를 가져옵니다.
upstage_api_key = os.getenv("UPSTAGE_API_KEY")

In [4]:
# Upstage API와 통신할 클라이언트를 초기화합니다.
# 제공해주신 예시 코드를 기반으로 설정합니다.
client = openai.OpenAI(
    base_url="https://api.upstage.ai/v1",
    api_key=upstage_api_key,
)

In [ ]:
response = client.chat.completions.create(
    model="solar-pro2",
    messages=[
        {
            "role": "user",
            "content": "동원 참치가 뭔지 알아?"
        }
    ]
)
    # 응답을 출력합니다.
print(response.choices[0].message.content)

동원 참치(Dongwon Tuna)는 한국의 대표적인 수산물 기업인 **동원산업**에서 생산하는 참치 통조림 브랜드입니다. 1982년 출시된 이후의 대표 상품으로, 국내 참치 시장에서 큰 점유율을 차지하며 대중적인 인기를 끌고 있습니다.

### 주요 특징:
1. **제품 라인업**:
   - 참치마요, 고추참치, 참치샐러드 등 다양한 맛의 통조림 제품.
   - 고급 라인으로 **동원 특선 참치** (통째로 사용한 스테이크 형태) 등도 있습니다.
   - 최근에는 편의점용 소포장 제품(예: 동원 한끼 참치)도 출시.

2. **원재료**:
   - 주로 **가다랑어**(Skipjack Tuna) 또는 **황다랑어**(Yellowfin Tuna)를 사용하며, 지속 가능한 어업을 위한 **MSC 인증** 제품도 일부 있습니다.

3. **특징**:
   - 한국 소비자의 입맛에 맞춘 양념(매콤한 맛, 마요네즈 등)이 강점.
   - 합리적인 가격대와 편의성으로 일상식으로 자주 소비됩니다.

4. **논란**:
   - 과거 일부 제품에서 **수은 함량** 논란이 있었으나, 현재는 국제 기준(WHO/FAO) 이하로 관리됩니다.
   - 환경단체로부터 **원양 어업의 과잉 어획** 문제 제기되기도 했습니다.

### 활용 팁:
- 밥과 비벼 먹거나, 김치찌개·볶음밥 재료로 활용.
- 해외에서도 한국인 이민자들이 찾는 대표 간식 중 하나입니다.

궁금한 특정 제품이 있다면 더 자세히 알려드릴 수 있어요! 🐟

1. 브랜드
2. 내용물 종류(살코기, 고추참치, 야채참치)
3. 용량
4. 가격

## 양반, 동원, 덴마크, 그릴리, 비비드,  만 뽑고 나머지 drop (GNC)

In [2]:
import pandas as pd
import numpy as np

df= pd.read_csv('data/학습용.csv', encoding='utf-8')

C:\Users\Admin\AppData\Local\Temp\ipykernel_12656\2162218747.py:4: DtypeWarning: Columns (6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('data/학습용.csv', encoding='utf-8')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36510 entries, 0 to 36509
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1차 카테고리      36510 non-null  object
 1   2차 카테고리      36510 non-null  object
 2   3차 카테고리      36510 non-null  object
 3   페이지          36510 non-null  int64
 4   상품명          36510 non-null  object
 5   3차 카테고리.1    36510 non-null  object
 6   식품유형         13 non-null     object
 7   용도           14 non-null     object
 8   추가방향         1 non-null      object
 9   중량 수치        0 non-null      float64
 10  묶음수량         0 non-null      float64
 11  총중량          0 non-null      float64
 12  10g당 가격      0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  중량 수치.1      15986 non-null  object
 15  중량 단위        15986 non-null  object
 16  수량           7872 non-null   object
 17  수량 단위        5879 non-null   object
 18  가격           36510 non-null  int64
 19  평점           36510 non-null  float64
 20  리뷰 수         36510 non-null  int64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  0 non-null      float64
 23  상품명.1        33817 non-null  object
dtypes: float64(8), int64(3), object(13)
memory usage: 6.7+ MB

In [4]:
# df의 상품명 컬럼에 양반, 동원, 덴마크, 그릴리, 비비드 중에 하나라도 들어간 행은 살려두고 나머지 열은 drop하고 인덱스 정리
df = df[df['상품명'].str.contains('양반|동원|덴마크|그릴리|비비드', na=False)]
df.reset_index(drop=True, inplace=True)
df

,1차 카테고리,2차 카테고리,3차 카테고리,페이지,상품명,3차 카테고리.1,식품유형,용도,추가방향,중량 수치,...,중량 수치.1,중량 단위,수량,수량 단위,가격,평점,리뷰 수,Unnamed: 21,Unnamed: 22,상품명.1
0,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 85g x 20캔,참치/연어통조림,통조림,반찬,간편식사,NaN,...,85,g,20,캔,31900,5.0,2304,NaN,NaN,동원참치 살코기 라이트스탠다드 85g x 20캔
1,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔,참치/연어통조림,통조림,반찬,NaN,NaN,...,"150, 200","g, g","10, 10","캔, 캔",49200,4.9,1467,NaN,NaN,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔
2,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 250g x 10캔,참치/연어통조림,통조림,반찬,NaN,NaN,...,250,g,10,캔,31490,4.9,984,NaN,NaN,동원참치 살코기 라이트스탠다드 150g x 5캔
3,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 85g x 10캔,참치/연어통조림,통조림,반찬,NaN,NaN,...,85,g,10,캔,16600,4.9,905,NaN,NaN,동원참치 살코기 라이트스탠다드 150g x 20캔
4,통조림/즉석/면류,통조림/캔,참치/연어통조림,1,동원참치 살코기 라이트스탠다드 150g x 20캔,참치/연어통조림,통조림,반찬,NaN,NaN,...,150,g,20,캔,50000,4.9,899,NaN,NaN,동원참치 살코기 라이트스탠다드 85g x 10캔
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,반려동식물,강아지 식품,습식사료,1,동원 뉴트리플랜 소프트뮨 습식 100g 닭가슴살 x 36개,습식사료,NaN,NaN,NaN,NaN,...,100,g,NaN,NaN,78900,0.0,0,NaN,NaN,NaN
1021,반려동식물,강아지 식품,습식사료,1,동원 뉴트리플랜 소프트뮨 습식 100g 참치와 닭가슴살 x 36개,습식사료,NaN,NaN,NaN,NaN,...,100,g,NaN,NaN,78900,0.0,0,NaN,NaN,NaN
1022,반려동식물,강아지 식품,습식사료,1,동원 뉴트리플랜 소프트뮨 화식 100g 소고기&야채 x 18개,습식사료,NaN,NaN,NaN,NaN,...,100,g,NaN,NaN,52900,0.0,0,NaN,NaN,NaN
1023,반려동식물,강아지 식품,습식사료,1,동원 뉴트리플랜 소프트뮨 화식 100g 닭가슴살&야채,습식사료,NaN,NaN,NaN,NaN,...,100,g,NaN,NaN,3300,0.0,0,NaN,NaN,NaN
1024,반려동식물,강아지 식품,캔/파우치,1,"[적립금5%][아르르 X 동원] 더 건강한 쮸르 2종 160p (참치&참치알, 닭&...",캔/파우치,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,64900,0.0,0,NaN,NaN,NaN

In [5]:
# 1차 카테고리의 모든 종류 확인
df['1차 카테고리'].unique()

array(['통조림/즉석/면류', '반려동식물', '김치/반찬/양념', '생활/유아동', '과자/떡/베이커리',
       '냉장/냉동/간편식', '과일/채소/쌀', '주방용품', '건강식품'], dtype=object)

In [6]:
df = df[~df['1차 카테고리'].isin(['반려동식물', '주방용품', '생활/유아동', '과일/채소/쌀', '건강식품'])]
df.reset_index(drop=True, inplace=True)

In [7]:
# df에서 1차 카테고리와 2차 카테고리와 3차 카테고리 컬럼과 페이지 컬럼 제거
df = df.drop(columns=['1차 카테고리', '2차 카테고리', '3차 카테고리', '페이지'])
df

,상품명,3차 카테고리.1,식품유형,용도,추가방향,중량 수치,묶음수량,총중량,10g당 가격,Unnamed: 13,중량 수치.1,중량 단위,수량,수량 단위,가격,평점,리뷰 수,Unnamed: 21,Unnamed: 22,상품명.1
0,동원참치 살코기 라이트스탠다드 85g x 20캔,참치/연어통조림,통조림,반찬,간편식사,NaN,NaN,NaN,NaN,NaN,85,g,20,캔,31900,5.0,2304,NaN,NaN,동원참치 살코기 라이트스탠다드 85g x 20캔
1,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,"150, 200","g, g","10, 10","캔, 캔",49200,4.9,1467,NaN,NaN,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔
2,동원참치 살코기 라이트스탠다드 250g x 10캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,250,g,10,캔,31490,4.9,984,NaN,NaN,동원참치 살코기 라이트스탠다드 150g x 5캔
3,동원참치 살코기 라이트스탠다드 85g x 10캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,85,g,10,캔,16600,4.9,905,NaN,NaN,동원참치 살코기 라이트스탠다드 150g x 20캔
4,동원참치 살코기 라이트스탠다드 150g x 20캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,150,g,20,캔,50000,4.9,899,NaN,NaN,동원참치 살코기 라이트스탠다드 85g x 10캔
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,[4% 적립금] 동원 참치다시 300gx30개 ( 1박스),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,g,30,개,89000,0.0,0,NaN,NaN,[해울림] 곶감 선물세트 7호_곶감20과_과당45~50g+아몬드300g+호두200g...
755,동원 참치다시 2kg,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,kg,NaN,NaN,26980,0.0,0,NaN,NaN,[해울림] 곶감 선물세트 실속 2호
756,[2+2] 동원 참치액 순 900g,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,g,NaN,NaN,25960,0.0,0,NaN,NaN,이음곶감 반건시 명품 7호 선물세트[반건시 65g~75g내외 30입 2.2kg미만]
757,동원 참치액 순 900gx3개,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,g,3,개,27000,0.0,0,NaN,NaN,이음곶감 반건시 명품 4호 선물세트[반건시 40g~45g내외 40입 1.8kg미만]
758,식자재 아울렛 동원홈푸드 파마산블렌드 227g,찹쌀가루/전분/기타가루,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227,g,NaN,NaN,7190,0.0,0,NaN,NaN,[하늘농가]순수국산 건도라지 50gX2팩

In [8]:
df.to_csv('data/1차_컨조인트_정리.csv', index=False, encoding='utf-8-sig')

In [9]:
df1 = pd.read_csv('data/1차_컨조인트_정리.csv', encoding='utf-8-sig')

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 759 entries, 0 to 758
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   상품명          759 non-null    object
 1   3차 카테고리.1    759 non-null    object
 2   식품유형         13 non-null     object
 3   용도           13 non-null     object
 4   추가방향         1 non-null      object
 5   중량 수치        0 non-null      float64
 6   묶음수량         0 non-null      float64
 7   총중량          0 non-null      float64
 8   10g당 가격      0 non-null      float64
 9   Unnamed: 13  0 non-null      float64
 10  중량 수치.1      755 non-null    object
 11  중량 단위        755 non-null    object
 12  수량           500 non-null    object
 13  수량 단위        496 non-null    object
 14  가격           759 non-null    int64
 15  평점           759 non-null    float64
 16  리뷰 수         759 non-null    int64
 17  Unnamed: 21  0 non-null      float64
 18  Unnamed: 22  0 non-null      float64
 19  상품명.1        759 non-null    object
dtypes: float64(8), int64(2), object(10)
memory usage: 118.7+ KB

In [11]:
df1.tail(10)

,상품명,3차 카테고리.1,식품유형,용도,추가방향,중량 수치,묶음수량,총중량,10g당 가격,Unnamed: 13,중량 수치.1,중량 단위,수량,수량 단위,가격,평점,리뷰 수,Unnamed: 21,Unnamed: 22,상품명.1
749,[4% 적립금] 동원 참치다시 1kgx10개(1박스),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,kg,10,개,66000,0.0,0,NaN,NaN,[농협] 한아름드린 달콤한 꿀 수박 6-7kg(특품)
750,[4%적립금] 동원 참치다시 2kg x 5개 ( 1박스 ),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,kg,5,개,65000,0.0,0,NaN,NaN,[희망농장] 국내산 머스크 멜론 8kg내외
751,동원 참치다시 300g,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,g,NaN,NaN,6980,0.0,0,NaN,NaN,[희망농장] 국내산 머스크 멜론 4kg(박스포함중량)
752,동원 하루미 국물의신 참치링 80g ( 20정),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80,g,NaN,NaN,6980,0.0,0,NaN,NaN,[24년 추석] 더 기다림 자연맛집 청도초당곶감 햇 반건시 프리미엄 명품4호 선물세...
753,동원 하루미 국물의신 멸치링 80g (20정),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80,g,NaN,NaN,6980,0.0,0,NaN,NaN,[24년 추석] 더 기다림 자연맛집 청도초당곶감 햇 반건시 프리미엄 명품12호 선물...
754,[4% 적립금] 동원 참치다시 300gx30개 ( 1박스),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,g,30,개,89000,0.0,0,NaN,NaN,[해울림] 곶감 선물세트 7호_곶감20과_과당45~50g+아몬드300g+호두200g...
755,동원 참치다시 2kg,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,kg,NaN,NaN,26980,0.0,0,NaN,NaN,[해울림] 곶감 선물세트 실속 2호
756,[2+2] 동원 참치액 순 900g,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,g,NaN,NaN,25960,0.0,0,NaN,NaN,이음곶감 반건시 명품 7호 선물세트[반건시 65g~75g내외 30입 2.2kg미만]
757,동원 참치액 순 900gx3개,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,g,3,개,27000,0.0,0,NaN,NaN,이음곶감 반건시 명품 4호 선물세트[반건시 40g~45g내외 40입 1.8kg미만]
758,식자재 아울렛 동원홈푸드 파마산블렌드 227g,찹쌀가루/전분/기타가루,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227,g,NaN,NaN,7190,0.0,0,NaN,NaN,[하늘농가]순수국산 건도라지 50gX2팩

In [41]:
df1.drop(columns=['평점', '리뷰 수'], inplace=True)

In [12]:
df1

,상품명,3차 카테고리.1,식품유형,용도,추가방향,중량 수치,묶음수량,총중량,10g당 가격,Unnamed: 13,중량 수치.1,중량 단위,수량,수량 단위,가격,평점,리뷰 수,Unnamed: 21,Unnamed: 22,상품명.1
0,동원참치 살코기 라이트스탠다드 85g x 20캔,참치/연어통조림,통조림,반찬,간편식사,NaN,NaN,NaN,NaN,NaN,85,g,20,캔,31900,5.0,2304,NaN,NaN,동원참치 살코기 라이트스탠다드 85g x 20캔
1,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,"150, 200","g, g","10, 10","캔, 캔",49200,4.9,1467,NaN,NaN,동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔
2,동원참치 살코기 라이트스탠다드 250g x 10캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,250,g,10,캔,31490,4.9,984,NaN,NaN,동원참치 살코기 라이트스탠다드 150g x 5캔
3,동원참치 살코기 라이트스탠다드 85g x 10캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,85,g,10,캔,16600,4.9,905,NaN,NaN,동원참치 살코기 라이트스탠다드 150g x 20캔
4,동원참치 살코기 라이트스탠다드 150g x 20캔,참치/연어통조림,통조림,반찬,NaN,NaN,NaN,NaN,NaN,NaN,150,g,20,캔,50000,4.9,899,NaN,NaN,동원참치 살코기 라이트스탠다드 85g x 10캔
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,[4% 적립금] 동원 참치다시 300gx30개 ( 1박스),분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,g,30,개,89000,0.0,0,NaN,NaN,[해울림] 곶감 선물세트 7호_곶감20과_과당45~50g+아몬드300g+호두200g...
755,동원 참치다시 2kg,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,kg,NaN,NaN,26980,0.0,0,NaN,NaN,[해울림] 곶감 선물세트 실속 2호
756,[2+2] 동원 참치액 순 900g,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,g,NaN,NaN,25960,0.0,0,NaN,NaN,이음곶감 반건시 명품 7호 선물세트[반건시 65g~75g내외 30입 2.2kg미만]
757,동원 참치액 순 900gx3개,분말/액상조미료,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,g,3,개,27000,0.0,0,NaN,NaN,이음곶감 반건시 명품 4호 선물세트[반건시 40g~45g내외 40입 1.8kg미만]
758,식자재 아울렛 동원홈푸드 파마산블렌드 227g,찹쌀가루/전분/기타가루,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227,g,NaN,NaN,7190,0.0,0,NaN,NaN,[하늘농가]순수국산 건도라지 50gX2팩

In [14]:
df1.to_csv('data/학습용_수정.csv', index=False, encoding='utf-8-sig')

- 참치캔 구매 상황 컨조인트 분석 설계
- 속성 및 속성 수준 <br>
속성 1: 참치 종류

수준: 살코기 참치, 고추 참치, 야채 참치

속성 2: 캔 용량

수준: 85g, 150g, 250g

속성 3: 묶음 수량

수준: 3개입, 10개입, 20개입

속성 4: 가격

수준: 10,000원, 25,000원, 45,000원

In [18]:
# 3차 카테고리.1 컬럼을 3차 카테고리로 변경
df1.rename(columns={'3차 카테고리.1': '3차 카테고리'}, inplace=True)
df1['3차 카테고리'].unique()

array(['참치/연어통조림', '햄/닭가슴살', '국/탕/찌개', '죽/스프', '골뱅이/수산통조림', '기타양념',
       '고등어/꽁치통조림', '과일/옥수수/팥', '아이반찬', '동원참치액', '떡볶이/떡류', '소금',
       '반찬/기타통조림', '고춧가루/액젓', '분말/액상조미료', '간장/고추장/된장/쌈장',
       '파스타/생면/건면/기타 면', '올리고당/물엿/조청/꿀', '부침가루/튀김가루/빵가루', '생지/냉동반죽', '짜장',
       '메인요리', '고기/찌개양념', '밑반찬', '봉지라면', '한식', '카레', '젓갈', '찹쌀가루/전분/기타가루'],
      dtype=object)

In [19]:
# '3차 카테고리' -> '식품유형' 매핑 규칙
food_type_map = {
    '참치/연어통조림': '통조림',
    '햄/닭가슴살': '가공육',
    '국/탕/찌개': '즉석조리식품',
    '죽/스프': '즉석조리식품',
    '골뱅이/수산통조림': '통조림',
    '기타양념': '양념',
    '고등어/꽁치통조림': '통조림',
    '과일/옥수수/팥': '통조림',
    '아이반찬': '반찬',
    '동원참치액': '소스',
    '떡볶이/떡류': '떡류',
    '소금': '양념',
    '반찬/기타통조림': '반찬',
    '고춧가루/액젓': '양념',
    '분말/액상조미료': '조미료',
    '간장/고추장/된장/쌈장': '장류',
    '파스타/생면/건면/기타 면': '면류',
    '올리고당/물엿/조청/꿀': '당류',
    '부침가루/튀김가루/빵가루': '가루류',
    '생지/냉동반죽': '냉동식품',
    '짜장': '소스',
    '메인요리': '즉석조리식품',
    '고기/찌개양념': '양념',
    '밑반찬': '반찬',
    '봉지라면': '라면',
    '한식': '즉석조리식품',
    '카레': '소스',
    '젓갈': '젓갈',
    '찹쌀가루/전분/기타가루': '가루류'
}

# '3차 카테고리' -> '용도' 매핑 규칙
usage_map = {
    '참치/연어통조림': '반찬/주재료',
    '햄/닭가슴살': '반찬/주재료',
    '국/탕/찌개': '간편식사',
    '죽/스프': '간편식사',
    '골뱅이/수산통조림': '안주/반찬',
    '기타양념': '조미료',
    '고등어/꽁치통조림': '반찬',
    '과일/옥수수/팥': '간식/요리재료',
    '아이반찬': '반찬',
    '동원참치액': '조미료',
    '떡볶이/떡류': '간식',
    '소금': '조미료',
    '반찬/기타통조림': '반찬',
    '고춧가루/액젓': '조미료',
    '분말/액상조미료': '조미료',
    '간장/고추장/된장/쌈장': '조미료',
    '파스타/생면/건면/기타 면': '주식',
    '올리고당/물엿/조청/꿀': '요리재료',
    '부침가루/튀김가루/빵가루': '요리재료',
    '생지/냉동반죽': '요리재료',
    '짜장': '요리재료',
    '메인요리': '메인요리',
    '고기/찌개양념': '조미료',
    '밑반찬': '반찬',
    '봉지라면': '간편식사',
    '한식': '메인요리',
    '카레': '요리재료',
    '젓갈': '반찬',
    '찹쌀가루/전분/기타가루': '요리재료'
}

In [ ]:
mapped_food_types = df1['3차 카테고리'].map(food_type_map)
mapped_usages = df1['3차 카테고리'].map(usage_map)


df1['식품유형'] = df1['식품유형'].fillna(mapped_food_types)
df1['용도'] = df1['용도'].fillna(mapped_usages)
print("'식품유형' 및 '용도'의 빈 값을 모두 채움")


print("\n--- 최종 결측치 확인 ---")
print(df1[['식품유형', '용도']].isnull().sum())

print("\n--- 데이터 변경 결과 (상위 10개) ---")
print(df1[['상품명', '3차 카테고리', '식품유형', '용도']].head(10))

output_file_path = 'data/학습용_카테고리_채우기_완료.csv'
df1.to_csv(output_file_path, index=False, encoding='utf-8-sig')
print(f"\n '{output_file_path}' 파일로 저장")

'식품유형' 및 '용도'의 빈 값을 모두 채웠습니다.

--- 최종 결측치 확인 ---
식품유형    0
용도      0
dtype: int64

--- 데이터 변경 결과 (상위 10개) ---
                                  상품명   3차 카테고리 식품유형     용도
0          동원참치 살코기 라이트스탠다드 85g x 20캔  참치/연어통조림  통조림     반찬
1  동원 라이트스탠다드 참치 150gx10캔+리챔 200gx10캔  참치/연어통조림  통조림     반찬
2         동원참치 살코기 라이트스탠다드 250g x 10캔  참치/연어통조림  통조림     반찬
3          동원참치 살코기 라이트스탠다드 85g x 10캔  참치/연어통조림  통조림     반찬
4         동원참치 살코기 라이트스탠다드 150g x 20캔  참치/연어통조림  통조림     반찬
5          동원참치 살코기 라이트스탠다드 150g x 5캔  참치/연어통조림  통조림     반찬
6                    동원 리챔 200g x 10캔    햄/닭가슴살  통조림     반찬
7         동원참치 살코기 라이트스탠다드 100g x 10캔  참치/연어통조림  통조림     반찬
8               동원참치 마일드참치 200g x 10캔  참치/연어통조림  통조림     반찬
9                 동원참치 고추참치 85g x 20캔  참치/연어통조림  통조림  반찬/양념

 'data/학습용_카테고리_채우기_완료.csv' 파일로 저장되었습니다.

In [43]:
import pandas as pd
import numpy as np
import re
from math import prod

print("데이터 처리 시작 (최종 수정)...")

try:
    # 1. 원본 데이터 불러오기
    df = pd.read_csv('학습용_수정.csv')
    print("✅ 원본 파일을 성공적으로 불러왔습니다.")

    # --- 최종 계산 함수 ---
    def get_final_calculations(row):
        name = str(row['상품명'])
        weight_str = str(row['중량 수치.1'])
        unit_str = str(row['중량 단위'])
        price = row['가격']
        
        # 기본값 및 초기화
        weight, quantity, total_weight, price_per_10g = np.nan, 1, np.nan, np.nan

        # 규칙 0: 복합 상품은 계산하지 않음
        if '+' in name or (isinstance(weight_str, str) and ',' in weight_str):
            return pd.Series([np.nan, np.nan, np.nan, np.nan])

        # 규칙 1: 무게 확정 (소수점 오류 수정)
        weight = pd.to_numeric(weight_str, errors='coerce')

        # 규칙 2: 묶음수량 확정 (괄호 오류 수정)
        # 괄호와 그 안의 내용을 모두 제거하여 계산에 영향을 주지 않도록 함
        name_no_parentheses = re.sub(r'\(.*\)', '', name)
        
        total_match = re.search(r'총\s*(\d+)', name_no_parentheses)
        if total_match:
            quantity = int(total_match.group(1))
        else:
            name_no_weight = re.sub(r'\b\d+(\.\d+)?\s*[gGkK][gG]\b', '', name_no_parentheses)
            q_units = r'(?:개|캔|병|봉|팩|입|박스)'
            q_matches = re.findall(r'(\d+)\s*' + q_units, name_no_weight)
            
            if q_matches:
                quantity = prod(int(n) for n in q_matches)
            else:
                x_matches = re.findall(r'[\sx\*]\s*(\d+)', name_no_weight)
                if x_matches:
                    quantity = prod(int(n) for n in x_matches)
                else:
                    quantity = 1
        
        # 규칙 3: 최종 계산
        if pd.notna(weight) and pd.notna(quantity):
            conversion_factor = 1000 if 'kg' in unit_str.lower() else 1
            total_weight = weight * quantity * conversion_factor
            if total_weight > 0:
                price_per_10g = round((price / total_weight) * 10, 2)

        return pd.Series([weight, quantity, total_weight, price_per_10g])

    # --- 모든 계산 다시 수행 ---
    df[['중량 수치', '묶음수량', '총중량', '10g당 가격']] = df.apply(get_final_calculations, axis=1, result_type='expand')
    
    # --- 최종 정리 ---
    food_type_map={'참치/연어통조림':'통조림','햄/닭가슴살':'가공육','국/탕/찌개':'즉석조리식품','죽/스프':'즉석조리식품','골뱅이/수산통조림':'통조림','기타양념':'양념','고등어/꽁치통조림':'통조림','과일/옥수수/팥':'통조림','아이반찬':'반찬','동원참치액':'소스','떡볶이/떡류':'떡류','소금':'양념','반찬/기타통조림':'반찬','고춧가루/액젓':'양념','분말/액상조미료':'조미료','간장/고추장/된장/쌈장':'장류','파스타/생면/건면/기타 면':'면류','올리고당/물엿/조청/꿀':'당류','부침가루/튀김가루/빵가루':'가루류','생지/냉동반죽':'냉동식품','짜장':'소스','메인요리':'즉석조리식품','고기/찌개양념':'양념','밑반찬':'반찬','봉지라면':'라면','한식':'즉석조리식품','카레':'소스','젓갈':'젓갈','찹쌀가루/전분/기타가루':'가루류'}
    usage_map={'참치/연어통조림':'반찬/주재료','햄/닭가슴살':'반찬/주재료','국/탕/찌개':'간편식사','죽/스프':'간편식사','골뱅이/수산통조림':'안주/반찬','기타양념':'조미료','고등어/꽁치통조림':'반찬','과일/옥수수/팥':'간식/요리재료','아이반찬':'반찬','동원참치액':'조미료','떡볶이/떡류':'간식','소금':'조미료','반찬/기타통조림':'반찬','고춧가루/액젓':'조미료','분말/액상조미료':'조미료','간장/고추장/된장/쌈장':'조미료','파스타/생면/건면/기타 면':'주식','올리고당/물엿/조청/꿀':'요리재료','부침가루/튀김가루/빵가루':'요리재료','생지/냉동반죽':'요리재료','짜장':'요리재료','메인요리':'메인요리','고기/찌개양념':'조미료','밑반찬':'반찬','봉지라면':'간편식사','한식':'메인요리','카레':'요리재료','젓갈':'반찬','찹쌀가루/전분/기타가루':'요리재료'}
    df['식품유형'] = df['식품유형'].fillna(df['3차 카테고리.1'].map(food_type_map))
    df['용도'] = df['용도'].fillna(df['3차 카테고리.1'].map(usage_map))
    df.rename(columns={'3차 카테고리.1': '3차 카테고리'}, inplace=True)
    
    final_columns = ['상품명', '3차 카테고리', '식품유형', '용도', '가격', '평점', '리뷰 수', '중량 수치', '묶음수량', '총중량', '10g당 가격']
    final_df = df[final_columns].copy()
    
    output_path = '진짜_최종_완성본2.csv'
    final_df.to_csv(output_path, index=False, encoding='utf-8-sig')

    print(f"\n🎉 모든 작업 완료! '{output_path}' 이름으로 파일이 저장되었습니다.")

except FileNotFoundError:
    print("\n❌ 오류: '학습용_수정.csv' 파일을 찾을 수 없습니다.")
except Exception as e:
    print(f"\n❌ 예상치 못한 오류가 발생했습니다: {e}")

데이터 처리 시작 (최종 수정)...
✅ 원본 파일을 성공적으로 불러왔습니다.

🎉 모든 작업 완료! '진짜_최종_완성본2.csv' 이름으로 파일이 저장되었습니다.

In [45]:
import pandas as pd
import numpy as np
import re
from math import prod

print("데이터 처리 시작 (최종 단순화 버전)...")

try:
    # 1. 원본 데이터 불러오기
    df = pd.read_csv('학습용_수정.csv')
    print("✅ 원본 파일을 성공적으로 불러왔습니다.")

    # --- 최종 계산 함수 ---
    def get_final_calculations(row):
        name = str(row['상품명'])
        weight_str = str(row['중량 수치.1'])
        unit_str = str(row['중량 단위'])
        price = row['가격']
        
        # 기본값 및 초기화
        weight, quantity, total_weight, price_per_10g = np.nan, 1, np.nan, np.nan

        # 규칙 0: 복합 상품은 계산하지 않음
        if '+' in name or (isinstance(weight_str, str) and ',' in weight_str):
            return pd.Series([np.nan, np.nan, np.nan, np.nan])

        # 규칙 1: 무게 확정
        weight = pd.to_numeric(weight_str, errors='coerce')

        # 규칙 2: 묶음수량 확정
        # 2-1: '총' 키워드가 있으면 최우선 적용
        total_match = re.search(r'총\s*(\d+)', name)
        if total_match:
            quantity = int(total_match.group(1))
        else:
            # 2-2: 무게와 괄호 정보를 완전히 제거
            name_no_parentheses = re.sub(r'\(.*\)', '', name)
            name_no_weight = re.sub(r'\b\d+(\.\d+)?\s*[gGkK][gG]\b', '', name_no_parentheses)
            
            # 2-3: '개, 캔, 박스' 등 명확한 수량 단위가 있는 숫자만 찾아 곱함
            quantity_units = r'(?:개|캔|병|봉|팩|입|박스)'
            quantity_matches = re.findall(r'(\d+)\s*' + quantity_units, name_no_weight)
            
            if quantity_matches:
                quantity = prod(int(n) for n in quantity_matches)
            else:
                # 2-4: 'x' 뒤에 있는 숫자 찾기 (수량 단위 없을 때)
                x_matches = re.findall(r'[\sx\*]\s*(\d+)', name_no_weight)
                if x_matches:
                     quantity = prod(int(n) for n in x_matches)
                else:
                    # 2-5: 위 규칙에 없으면 무조건 1개로 처리
                    quantity = 1
        
        # 규칙 3: 최종 계산
        if pd.notna(weight) and pd.notna(quantity):
            conversion_factor = 1000 if 'kg' in unit_str.lower() else 1
            total_weight = weight * quantity * conversion_factor
            if total_weight > 0:
                price_per_10g = round((price / total_weight) * 10, 2)

        return pd.Series([weight, quantity, total_weight, price_per_10g])

    # --- 모든 계산 다시 수행 ---
    calculated_df = df.apply(get_final_calculations, axis=1, result_type='expand')
    df[['중량 수치', '묶음수량', '총중량', '10g당 가격']] = calculated_df
    
    # --- 최종 정리 ---
    food_type_map={'참치/연어통조림':'통조림','햄/닭가슴살':'가공육','국/탕/찌개':'즉석조리식품','죽/스프':'즉석조리식품','골뱅이/수산통조림':'통조림','기타양념':'양념','고등어/꽁치통조림':'통조림','과일/옥수수/팥':'통조림','아이반찬':'반찬','동원참치액':'소스','떡볶이/떡류':'떡류','소금':'양념','반찬/기타통조림':'반찬','고춧가루/액젓':'양념','분말/액상조미료':'조미료','간장/고추장/된장/쌈장':'장류','파스타/생면/건면/기타 면':'면류','올리고당/물엿/조청/꿀':'당류','부침가루/튀김가루/빵가루':'가루류','생지/냉동반죽':'냉동식품','짜장':'소스','메인요리':'즉석조리식품','고기/찌개양념':'양념','밑반찬':'반찬','봉지라면':'라면','한식':'즉석조리식품','카레':'소스','젓갈':'젓갈','찹쌀가루/전분/기타가루':'가루류'}
    usage_map={'참치/연어통조림':'반찬/주재료','햄/닭가슴살':'반찬/주재료','국/탕/찌개':'간편식사','죽/스프':'간편식사','골뱅이/수산통조림':'안주/반찬','기타양념':'조미료','고등어/꽁치통조림':'반찬','과일/옥수수/팥':'간식/요리재료','아이반찬':'반찬','동원참치액':'조미료','떡볶이/떡류':'간식','소금':'조미료','반찬/기타통조림':'반찬','고춧가루/액젓':'조미료','분말/액상조미료':'조미료','간장/고추장/된장/쌈장':'조미료','파스타/생면/건면/기타 면':'주식','올리고당/물엿/조청/꿀':'요리재료','부침가루/튀김가루/빵가루':'요리재료','생지/냉동반죽':'요리재료','짜장':'요리재료','메인요리':'메인요리','고기/찌개양념':'조미료','밑반찬':'반찬','봉지라면':'간편식사','한식':'메인요리','카레':'요리재료','젓갈':'반찬','찹쌀가루/전분/기타가루':'요리재료'}
    df['식품유형'] = df['식품유형'].fillna(df['3차 카테고리.1'].map(food_type_map))
    df['용도'] = df['용도'].fillna(df['3차 카테고리.1'].map(usage_map))
    df.rename(columns={'3차 카테고리.1': '3차 카테고리'}, inplace=True)
    
    final_columns = ['상품명', '3차 카테고리', '식품유형', '용도', '가격', '평점', '리뷰 수', '중량 수치', '묶음수량', '총중량', '10g당 가격']
    final_df = df[final_columns].copy()
    
    output_path = '최종_완성본4.csv'
    final_df.to_csv(output_path, index=False, encoding='utf-8-sig')

    print(f"\n🎉 모든 작업 완료! '{output_path}' 이름으로 파일이 저장되었습니다.")

except FileNotFoundError:
    print("\n❌ 오류: '학습용_수정.csv' 파일을 찾을 수 없습니다.")
except Exception as e:
    print(f"\n❌ 예상치 못한 오류가 발생했습니다: {e}")

데이터 처리 시작 (최종 단순화 버전)...
✅ 원본 파일을 성공적으로 불러왔습니다.

🎉 모든 작업 완료! '최종_완성본4.csv' 이름으로 파일이 저장되었습니다.